# -*- coding: utf-8 -*-
"""MNIST_Digit_Classification_using_Deep_Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZuFJN6cr5xLov06SmE1NP72eFhTAVx-W

# MNIST Digit Classification using Deep Learning (Neural Network)

Importing Essential Libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import cv2
from google.colab.patches import cv2_imshow
from PIL import Image
import tensorflow as tf
tf.random.set_seed(3)
from tensorflow import keras
from keras.datasets import mnist
from tensorflow.math import confusion_matrix

"""Loading MNSIT data from keras.datasets"""

(X_train, Y_train), (X_test, Y_test) =  mnist.load_data()

type(X_train)

print(X_train.shape, Y_train.shape, X_test.shape, Y_test.shape)

"""Training Data = 60,000 images
Test Data = 10,000 images

Image Dimension => 28 X 28
Grayscale Image => 1 channel
"""

# printing the 10th image
print(X_train[10])

print(X_train[10].shape)

# displaying the image
plt.imshow(X_train[40])
plt.show()

# print the corresponding label
print(Y_train[40])

"""Image labels"""

print(Y_train.shape, Y_test.shape)

print(np.unique(Y_train))

print(np.unique(Y_test))

"""We can use these labels as they are or we can also apply one-hot encoding

All the images have the same dimensions in the dataset, if they were not, we have to resize all the images to a common distribution
"""

X_train = X_train/255
X_test = X_test/255

"""Printing the 10th image"""

print(X_train[10])

"""## Builiding the Neural Network

Setting up the layers of NN
"""

model = keras.Sequential([
                          keras.layers.Flatten(input_shape=(28,28)),
                          keras.layers.Dense(50, activation='relu'),
                          keras.layers.Dense(50, activation='relu'),
                          keras.layers.Dense(10, activation='sigmoid')
])

"""Compiling the Model"""

model.compile(optimizer='adam',
              loss = 'sparse_categorical_crossentropy',
              metrics=['accuracy'])

"""Training the Model"""

model.fit(X_train, Y_train, epochs=10)

"""Training data accuracy = 98.8%

Accuracy on Test Data
"""

loss, accuracy = model.evaluate(X_test, Y_test)
print(accuracy)

"""Test Data Accuracy : 97.3 %"""

print(X_test.shape)

"""First data in X_test"""

plt.imshow(X_test[0])
plt.show()

print(Y_test[0])

Y_pred = model.predict(X_test)

print(Y_pred.shape)

print(Y_pred[0])

"""model.predict() gives the prediction probability of each class for that data point

Converting predicion probabilities to class label
"""

label_for_first_test_image = np.argmax(Y_pred[0])
print(label_for_first_test_image)

"""Doing the same thing for all test data points"""

Y_pred_labels = [np.argmax(i) for i in Y_pred]
print(Y_pred_labels)

"""Y_test => True labels

Y_pred_labels => Predicted labels

Confusion Matrix
"""

conf_mat = confusion_matrix(Y_test, Y_pred_labels)

print(conf_mat)

"""Visualizaing True Labels vs Predicted Labels"""

plt.figure(figsize=(15,7))
sns.heatmap(conf_mat, annot=True, fmt='d', cmap='Blues')
plt.ylabel('True Labels')
plt.xlabel('Predicted Labels')

"""Building a predicting system"""

#Loading the prediction image
input_image_path = '/content/MNIST_digit.png'

input_image = cv2.imread(input_image_path)

type(input_image)

print(input_image)

cv2_imshow(input_image)

"""Analyzing input image"""

input_image.shape

"""Grayscaling"""

grayscale = cv2.cvtColor(input_image, cv2.COLOR_RGB2GRAY)

grayscale.shape

input_image_resize = cv2.resize(grayscale, (28, 28))

input_image_resize.shape

cv2_imshow(input_image_resize)

"""Scaling the image"""

input_image_resize = input_image_resize/255

type(input_image_resize)

image_reshaped = np.reshape(input_image_resize, [1,28,28])

input_prediction = model.predict(image_reshaped)
print(input_prediction)

input_pred_label = np.argmax(input_prediction)

print(input_pred_label)

"""Complete Predicting System"""

input_image_path = input('Path of the image to be predicted: ')

input_image = cv2.imread(input_image_path)

cv2_imshow(input_image)

grayscale = cv2.cvtColor(input_image, cv2.COLOR_RGB2GRAY)

input_image_resize = cv2.resize(grayscale, (28, 28))

input_image_resize = input_image_resize/255

image_reshaped = np.reshape(input_image_resize, [1,28,28])

input_prediction = model.predict(image_reshaped)

input_pred_label = np.argmax(input_prediction)

print('The Handwritten Digit is recognised as ', input_pred_label)